# Generated by Django 5.0.3 on 2024-04-03 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="_id",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="numReviews",
        ),
    ]
